# Site settings
baseurl = "http://3dsim.github.io/corporate-site/"
languageCode = "en-us"
title = "Creating the world’s fastest framework for solving multi-physics/multi-scale simulation problems."
copyright = "All rights reserved - 2016"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "3DSIM"
	description = ""

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "ryan.walls@3dsim.com"

    # Link custom assets relative to /static
    custom_css = []
    custom_js  = []


	# Navigation
	[params.navigation]
		brand = "3DSIM"
		services = "Features"
		portfolio = "Products"
		about = "About"
		team = "Team"
		contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    # postpended links
    [[menu.postpend]]
        url = "http://3dsim.github.io"
        name = "Software Blog"
        weight = 10


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
    # Additive Manufacturing Insight = Additive Manufacturing Success
    # Facing Challenges in Additive Manufacturing?
    # Build Failures?
    # Insight = Success
    # Do you need more insight?
		title = "Challenges in Additive Manufacturing?<br/>Insight = Success"

		subtitle = "3DSIM"
		buttonText = "Tell me more"


	# Services section
	[params.services]
    enable = true
		title = "Features"
		subtitle = "Based upon years of work by the world’s leading researchers in Additive Manufacturing, we’re building software solutions to provide unprecedented insight into metal 3D printing processes - all at speeds unreachable by current simulation tools."

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-rocket"
                title = "Fast"
                description = "Using a combination of a multi-scale mesh that dynamically moves with the energy source and novel mathematical formulations."

            [[params.services.row.list]]
                icon = "fa-cloud"
                title = "Cloud Based"
                description = "Providing no hassle updates with nothing to install on your local machine."

            [[params.services.row.list]]
                icon = "fa-lock"
                title = "Secure"
                description = "SSL encryption on every page combined with industry best practices."

	# Portfolio section
	[params.portfolio]
        enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Products"
		subtitle = "Powerful webapps delivered directly to you in the cloud"

		[params.portfolio.modal]
            client = "Link"
            date = "Date"
            category = "Category"
            buttonText = "Close"


    # About section
	[params.about]
        enable = true
		title = "About"
		subtitle = "Our journey from idea to product"
		endpoint = "Be part<br>of our<br>story!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			date = "2009-2011"
			title = "Our Humble Beginnings"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "2.jpg"
			date = "March 2011"
			title = "An Agency is Born"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "3.jpg"
			date = "December 2012"
			title = "Our Humble Beginnings"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "4.jpg"
			date = "July 2014"
			title = "Phase Two Expansion"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


	# Team section
	[params.team]
        enable = true
		title = "Our amazing team"
		subtitle = "Changing the simulation world from a little ski town."
    # TODO core beliefs here
		description = ""

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "brentstucker.jpg"
			name = "Brent Stucker"
			position = "CEO and Co-Founder"
			social = [
				["fa-linkedin", "https://www.linkedin.com/in/brent-stucker-040530b"]
			]

		[[params.team.members]]
			img = "deepankarpal.jpg"
			name = "Deepankar Pal"
			position = "Chief Scientist and Co-Founder"
			social = [
				["fa-linkedin", "https://www.linkedin.com/in/deepankar-pal-03310212"]
			]

		[[params.team.members]]
			img = "nachiketpatil.jpg"
			name = "Nachiket Patil"
			position = "Inventor and Co-Founder"
			social = [
				["fa-linkedin", "https://www.linkedin.com/in/patilnachiket"]
			]

	# Client section
    [params.clients_list]
        enable = true

    	# All the clients' logos are stored under 'static/img/logos'.
    	# Replace them with your clients's logos.
    	[[params.clients]]
    		logo = "envato.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "designmodo.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "themeforest.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "creative-market.jpg"
    		link = "#"


	# Contact section
	[params.contact]
        enable = true
		title = "Start simulating today"
		subtitle  = "Fill out this form and someone from our onboarding team will contact you"
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
        enable = true
		copyright = "All rights reserved - 2016"

		# [[params.footer.social]]
		# 	icon = "fa-twitter"
		# 	link = "#"
    #
		# [[params.footer.social]]
		# 	icon = "fa-facebook"
		# 	link = "#"
    #
		# [[params.footer.social]]
		# 	icon = "fa-linkedin"
		# 	link = "#"

		[[params.footer.quicklinks]]
			text = "Privacy Policy"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Terms of Use"
			link = "#"
