# Site settings
baseurl = "https://3dsim.github.io/corporate-site/"
languageCode = "en-us"
title = "Additive Manufacturing Simulation"
copyright = "All rights reserved - 2017"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-83914032-1"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "3DSIM"
	description = ""

	# Google Search Console
	googleSiteVerification = "UPJ0PhYARib6LXSPSvUZakBf3RrG3aXu_ZBFJPmjWMI"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "ryan.walls@3dsim.com"

    # Link custom assets relative to /static
    custom_css = ["css/magnific-popup.css"]
    custom_js  = ["https://checkout.stripe.com/checkout.js","js/typed.min.js","js/jquery.magnific-popup.min.js","js/site.js"]


	# Navigation
	[params.navigation]
		brand = "3DSIM"
		services = "Features"
		portfolio = "Products"
		about = "About"
		team = "Team"
		contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    # postpended links
    [[menu.postpend]]
        url = "http://learn.3dsim.com"
        name = "Learn More"
        weight = 5
    [[menu.postpend]]
        url = "https://app.3dsim.com"
        name = "Login"
        weight = 20

	[params.callToAction]
		url = "https://simulation.3dsim.com/signup"
		name = "Free Trial"
		enable = true

	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Seize Control of Your Additive Manufacturing Process"
		subtitle = "Detailed science^500 <i class=\"fa fa-caret-right\"></i> ^1000Production success"
		buttonText = "Subscribe Now"
		buttonLink = "https://simulation.3dsim.com/signup"
		videoButtonEnabled = false
    	videoLink = "https://www.youtube.com/watch?v=pKk_krg2DC4"
    	videoButtonText = "<i class=\"fa fa-play-circle\"></i> Play Video"
		announcementEnabled = true
		announcementDate = "November 15, 2017"
		announcementText = "Sigma Labs and 3DSIM release simulation thermal sensors"
		announcementLinkText = "Read the press release"
		announcementLinkUrl = "http://learn.3dsim.com/sigma-labs-3dsim-release-simulation-capability-model-thermal-sensors-metal-additive-manufacturing-processes/"


	# Services section
	[params.services]
    	enable = false
		title = "Features"
		subtitle = "Providing unprecedented insight into metal 3D printing processes."

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-rocket"
                title = "Fast"
                description = "Innovative meshing techniques and novel mathematical formulations implemented in highly efficient software."

            [[params.services.row.list]]
                icon = "fa-object-group"
                title = "Multi-Physics"
                description = "Multi-scale solvers tuned to the physics of additive manufacturing."

            [[params.services.row.list]]
                icon = "fa-thumbs-up"
                title = "User Friendly"
                description = "Modern user interface providing access to cutting edge simulation power without the need for specialized training."

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-cubes"
                title = "Scalable"
                description = "Leveraging the power of Amazon Web Services to provide nearly unlimited scalability for even the largest customer."

            [[params.services.row.list]]
                icon = "fa-cloud"
                title = "Cloud Based"
                description = "Providing no hassle updates with nothing to install on your local machine."

            [[params.services.row.list]]
                icon = "fa-lock"
                title = "Secure"
                description = "SSL encryption on every page combined with industry best practices."

	# Portfolio section
	[params.portfolio]
        enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Products"
		subtitle = "Powerful simulation tools delivered directly to you in the cloud"

		[params.portfolio.modal]
            client = "Link"
            date = "Date"
            category = "Category"
            buttonText = "Close"

    # About section
	[params.about]
        enable = true
		title = "3DSIM"
		subtitle = "About us"
		endpoint = "Be part<br>of our<br>story!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			date = "2009-2013"
			title = "Research Beginnings"
			description = "Intensive period of academic research, tackling the problems related to simulating a full scale additive manufacturing process."

		[[params.about.events]]
			img = "baby_skis_small.jpg"
			date = "2014"
			title = "3DSIM is Born"
			description = "Critical mass of research success resulted in the formation of 3DSIM.  First funding round completed, initial team assembled, and work building the world's fastest simulation framework began."

		[[params.about.events]]
			img = "techcenter_small.jpg"
			date = "January 2015"
			title = "Accelerated Growth"
			description = "Relocated the company to Park City, UT to access the large Salt Lake City technical talent pool."

		[[params.about.events]]
			img = "team_small.png"
			date = "2015-2016"
			title = "Building Our Vision"
			description = "Grew the team by 4x.  Completed structural mechanics and thermal solvers.  Built cloud delivery framework.  Engaged alpha users."

    	[[params.about.events]]
			img = "launch_small.jpg"
			date = "September 2016"
			title = "exaSIM Beta Launch"
			description = "The first easy to use cloud-based simulation tool for predicting stress and distortion in metal laser sintering."

    	[[params.about.events]]
			img = "eclipse.jpg"
			date = "September 2017"
			title = "exaSIM Ultimate Launch"
			description = "The only AM simulation tool incorporating full part thermal history."



	# Team section
	[params.team]
        enable = false
		title = "The 3DSIM Team"
		subtitle = "Changing the simulation world from a little ski town."
    # TODO core beliefs here
		description = ""

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "brentstucker.jpg"
			name = "Brent Stucker"
			position = "CEO and Co-Founder"
			social = [
				["fa-linkedin", "https://www.linkedin.com/in/brent-stucker-040530b"]
			]

		[[params.team.members]]
			img = "deepankarpal.jpg"
			name = "Deepankar Pal"
			position = "Chief Scientist and Co-Founder"
			social = [
				["fa-linkedin", "https://www.linkedin.com/in/deepankar-pal-03310212"]
			]

		[[params.team.members]]
			img = "nachiketpatil.jpg"
			name = "Nachiket Patil"
			position = "Inventor and Co-Founder"
			social = [
				["fa-linkedin", "https://www.linkedin.com/in/patilnachiket"]
			]

	# Client section
    [params.customers]
        enable = true
		title = "Join our Growing List of Customers & Partners"


	# Contact section
	[params.contact]
        enable = true
		title = "Still have questions?"
		subtitle  = "Schedule a demo, request more information, or connect with our team."
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
    enable = true
		copyright = "&#169;Copyright 2017 3DSIM LLC, All Rights Reserved"
    contact = "<i class=\"fa fa-map-marker\"></i> 1794 Olympic Parkway, Park City, UT 84098 <br/><i class=\"fa fa-phone\"></i> (435) 602-4033"

		# [[params.footer.social]]
		# 	icon = "fa-twitter"
		# 	link = "#"
    #
		# [[params.footer.social]]
		# 	icon = "fa-facebook"
		# 	link = "#"
    #
		# [[params.footer.social]]
		# 	icon = "fa-linkedin"
		# 	link = "#"

		[[params.footer.quicklinks]]
			text = "Privacy Policy"
			link = "#"
